# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: F401

from allegro.allegro import Boid, Dimensions, Universe, create_boids_with_random_positions
__all__ = [
    "Boid",
    "Dimensions",
    "Universe",
    "create_boids_with_random_positions",
]
