# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "Boid",
    "Dimensions",
    "DistanceMode",
    "FitMode",
    "Pitch",
    "PitchClassSet",
    "Universe",
    "VoiceLeading",
    "Voicing",
    "bouncing_ball",
    "bpm_to_seconds",
    "create_boids_with_random_positions",
    "fit",
    "fit_list",
    "interval_class",
    "invert",
    "invert_ordered_set",
    "keynum_to_pitch",
    "quadratic_bouncing_ball",
    "quantize",
    "rhythm_to_seconds",
    "transpose",
    "transpose_ordered_set",
    "voicings_from_pc_set",
    "voicings_from_pc_set_in_keynum_range",
    "voicings_from_pc_set_within_span",
]

@typing.final
class Boid:
    r"""
    Represent a single boid in the flock.
    
    A ``Boid`` stores a 3D position and a 3D velocity.
    
    Parameters:
        position (list[float]):
            Initial position as ``[x, y, z]``. Must contain exactly 3 elements.
        velocity (list[float]):
            Initial velocity as ``[vx, vy, vz]``. Must contain exactly 3 elements.
    
    Raises:
        ValueError:
            If ``position`` does not contain exactly 3 elements.
        ValueError:
            If ``velocity`` does not contain exactly 3 elements.
    
    Examples:
        >>> boid = Boid([0.0, 0.0, 0.0], [1.0, 0.0, 0.0])
        >>> boid.position()
        (0.0, 0.0, 0.0)
        >>> boid.velocity()
        (1.0, 0.0, 0.0)
    """
    def __new__(cls, position: typing.Sequence[builtins.float], velocity: typing.Sequence[builtins.float]) -> Boid: ...
    def position(self) -> tuple[builtins.float, builtins.float, builtins.float]:
        r"""
        Return the boid position as ``(x, y, z)``.
        
        Returns:
            tuple[float, float, float]:
                The current position.
        """
    def velocity(self) -> tuple[builtins.float, builtins.float, builtins.float]:
        r"""
        Return the boid velocity as ``(vx, vy, vz)``.
        
        Returns:
            tuple[float, float, float]:
                The current velocity.
        """

@typing.final
class Dimensions:
    r"""
    ``Dimensions`` describes the axis-bounded bounding box that contains the
    flock. The bounds are used by ``Universe`` to steer boids back toward the
    interior when they move outside coordinates.
    
    Parameters:
        x_min (float):
            Minimum x coordinate.
        x_max (float):
            Maximum x coordinate.
        y_min (float):
            Minimum y coordinate.
        y_max (float):
            Maximum y coordinate.
        z_min (float):
            Minimum z coordinate.
        z_max (float):
            Maximum z coordinate.
    
    Attributes:
        x_min (float):
            Minimum x coordinate.
        x_max (float):
            Maximum x coordinate.
        y_min (float):
            Minimum y coordinate.
        y_max (float):
            Maximum y coordinate.
        z_min (float):
            Minimum z coordinate.
        z_max (float):
            Maximum z coordinate.
    
    Raises:
        ValueError: If any minimum is greater than or equal to its maximum
        (e.g. x_min >= x_max).
    
    Examples:
        >>> dims = Dimensions(-500.0, 500.0, -500.0, 500.0, -500.0, 500.0)
    """
    @property
    def x_min(self) -> builtins.float: ...
    @x_min.setter
    def x_min(self, value: builtins.float) -> None: ...
    @property
    def x_max(self) -> builtins.float: ...
    @x_max.setter
    def x_max(self, value: builtins.float) -> None: ...
    @property
    def y_min(self) -> builtins.float: ...
    @y_min.setter
    def y_min(self, value: builtins.float) -> None: ...
    @property
    def y_max(self) -> builtins.float: ...
    @y_max.setter
    def y_max(self, value: builtins.float) -> None: ...
    @property
    def z_min(self) -> builtins.float: ...
    @z_min.setter
    def z_min(self, value: builtins.float) -> None: ...
    @property
    def z_max(self) -> builtins.float: ...
    @z_max.setter
    def z_max(self, value: builtins.float) -> None: ...
    def __new__(cls, x_min: builtins.float, x_max: builtins.float, y_min: builtins.float, y_max: builtins.float, z_min: builtins.float, z_max: builtins.float) -> Dimensions: ...

@typing.final
class Pitch:
    r"""
    A concrete pitch identified by a MIDI key number.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Scientific pitch notation (e.g. ``'C4'`` for MIDI key number 60).
        """
    @property
    def keynum(self) -> builtins.int:
        r"""
        MIDI key number for this pitch.
        """

@typing.final
class PitchClassSet:
    r"""
    A collection of distinct pitch classes.
    
    `PitchClassSet` represents a collection of distinct pitch classes,
    where each pitch class must be unique and in the range 0–11.
    
    Notes:
        Although this type represents an unordered set, the current input order
        is preserved internally. Methods that require sorted pitch classes sort
        internally before computing their results.
    """
    @property
    def pitch_classes(self) -> builtins.list[builtins.int]:
        r"""
        Get the pitch classes in this set.
        
        The returned list contains the pitch classes currently stored by the set.
        Values are represented as integers modulo 12, where 0 is C, 1 is C♯/D♭,
        and so on.
        
        Returns:
            list[int]: The pitch classes in the set.
        
        Example:
            >>> pcs.pitch_classes
            [0, 2, 4, 7]
        """
    @property
    def normal_form(self) -> builtins.list[builtins.int]:
        r"""
        Compute the normal form of the pitch-class set.
        
        The normal form is the most "compact" ordering of the set when treated as
        an ascending scale within a single octave.
        
        Algorithm:
            1. Generate all cyclic rotations of the sorted pitch classes. Each
               rotation is interpreted as an ascending pitch sequence (wrapping
               earlier elements up an octave).
        
            2. Select the rotation(s) with the smallest total span:
               (last_pitch - first_pitch).
        
            3. If multiple candidates remain, break ties by comparing intervals
               from the left:
                   - Then (second-to-last - first), if still tied,
                   - Then (third-to-last - first), and so on
               Keep only the most "left-packed" (most compact toward the beginning).
        
            4. If a tie still remains, choose the ordering whose first pitch class
               is smallest.
        
            5. Finally, wrap all pitches modulo 12 to return pitch classes.
        
        Returns:
            list[int]: The normal form of the set as pitch classes in the range 0–11.
        
        Notes:
            This implementation follows the standard post-tonal theory definition
            (Rahn/Straus style) and corresponds to the algorithm described in
            `src/specs/pitchclass.md`.
        """
    @property
    def prime_form(self) -> builtins.list[builtins.int]:
        r"""
        Compute the Rahn prime form of the pitch-class set.
        
        This computes the normal form of the set and the normal form of its
        inversion, transposes both so that they begin on 0, and returns the
        lexicographically smaller result.
        
        Returns:
            list[int]: The prime form of the set as pitch classes in the range 0–11.
        """
    @property
    def forte_num(self) -> builtins.str:
        r"""
        Look up the Forte number for the pitch-class set.
        
        The set is converted to Rahn prime form and then matched against the Forte
        catalog.
        
        Returns:
            str: The Forte number for the set.
        
        Raises:
            ValueError: If the prime form is not found in the Forte catalog.
        """
    @property
    def interval_vector(self) -> builtins.list[builtins.int]:
        r"""
        Compute the Forte interval-class vector for this pitch-class set.
        
        The interval-class vector is a six-element count of the unordered pitch-class
        intervals present in the set. For each unordered pair of distinct pitch
        classes, the smaller directed interval is computed modulo 12, mapped to an
        interval class from 1 through 6, and counted at index `ic - 1`.
        
        Returns:
            list[int]: The interval vector of a pitch-class set, where each position
            corresponds to interval classes 1 through 6.
        
        Example:
            >>> pcs.interval_vector
            [0, 0, 1, 1, 1, 0]
        """
    def __new__(cls, pitch_classes: typing.Sequence[builtins.int]) -> PitchClassSet:
        r"""
        Create a new pitch-class set.
        
        Args:
            pitch_classes (list[int]): The pitch classes in the set.
                Each value must be unique and in the range 0–11.
                At most 12 pitch classes are allowed.
        
        Returns:
            PitchClassSet: A new pitch-class set.
        
        Raises:
            ValueError: If more than 12 pitch classes are provided.
            ValueError: If any pitch class is duplicated.
            ValueError: If any pitch class is outside the range 0–11.
        """
    def subsets(self, min_size: builtins.int = 0) -> builtins.list[PitchClassSet]:
        r"""
        Generate all subsets of the pitch-class set.
        
        Args:
            min_size (int, optional): Only include subsets with at least this many pitch classes.
                Defaults to ``0`` (full powerset). Any value greater than the number of pitch classes
                in the set will return an empty list.
        
        Throws:
            OverflowError: If ``min_size`` is negative.
        
        Returns:
            list[PitchClassSet]: Subsets of the pitch-class set whose length is at least ``min_size``.
        """
    def count_common_tones_under_tn(self, tn: builtins.int) -> builtins.int:
        r"""
        Count how many pitch classes are shared between this set and its transposition by ``tn``
        semitones (``Tn``, mod 12).
        
        For ``tn ≡ 0 (mod 12)``, no pitches change, so the count is the cardinality
        of the set.
        
        Otherwise the we use the values in the set's interval-class vector and look up the value
        according to the interval class of tn.
        
        For example, if tn is 10, then the interval class is 2, so we look up the
        value at index ``1`` in the interval-class vector (i.e. ``iv[1]``).
        (It's at index 1, because we don't store interval class 0 in the interval-class vector.)
        
        Under **tritone** transposition, i.e. ``Tn6``, common tones are **twice** the entry in
        the interval-class vector.
        See Open Music Theory, "Common Tones under Transposition"
        (<https://openmusictheory.github.io/commonTonesUnderTransposition.html>).
        
        Args:
            tn (int): Transposition level in semitones (any integer -128..=127; reduced mod 12).
        
        Returns:
            int: Number of common pitch classes between pitch-class set and its transposition by ``tn``.
        """
    def transpose_by(self, tn: builtins.int) -> PitchClassSet:
        r"""
        Transpose the pitch-class set by a given number of semitones.
        
        The pitch-class set is transposed by the given number of semitones and the
        result is wrapped modulo 12.
        
        Args:
            tn (int): The number of semitones to transpose by.
                Must be in the range -11 to 11.
        """

@typing.final
class Universe:
    r"""
    Represent a boids simulation and its rule parameters.
    
    ``Universe`` stores the flock, the world bounds, and the parameters that
    control cohesion, separation, alignment, boundary steering, and optional
    speed limiting.
    
    Call ``step()`` to advance the simulation by one discrete time step.
    
    Parameters:
        flock (list[Boid]):
            Initial flock of boids.
        dimensions (Dimensions):
            World bounds for the simulation.
        cohesion_factor (float):
            Strength of cohesion. Higher values pull boids more strongly toward
            the perceived center of mass of the flock.
        separation_distance (float):
            Distance threshold used for separation. Boids closer than this
            distance push away from one another.
        alignment_factor (float):
            Strength of alignment. Higher values steer boids more strongly
            toward the perceived average flock velocity.
        bound_steer (float):
            Fixed steering amount applied when a boid crosses a world boundary.
        speed_limit (float, optional):
            Maximum allowed speed magnitude. If ``None``, no speed limit is
            applied.
    
    Notes:
        The simulation applies the following updates in order:
    
        1. Fly towards perceived center of mass
        2. Move away from close by objects
        3. Match perceived speed of flock
        4. Bound position
        5. Limit velocity
        6. Update position
    
    Examples:
        >>> dims = Dimensions(-500.0, 500.0, -500.0, 500.0, -500.0, 500.0)
        >>> flock = [Boid([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]), Boid([100.0, 0.0, 0.0], [0.0, 0.0, 0.0])]
        >>> universe = Universe(
        ...     flock,
        ...     dims,
        ...     cohesion_factor=0.01,
        ...     separation_distance=100.0,
        ...     alignment_factor=0.125,
        ...     bound_steer=10.0,
        ...     speed_limit=10.0,
        ... )
    """
    def __new__(cls, flock: typing.Sequence[Boid], dimensions: Dimensions, cohesion_factor: builtins.float, separation_distance: builtins.float, alignment_factor: builtins.float, bound_steer: builtins.float, speed_limit: typing.Optional[builtins.float] = None) -> Universe: ...
    def step(self) -> builtins.list[Boid]:
        r"""
        Advance the flock by one time step.
        
        This method applies the boids rules to every boid in the universe,
        updates velocities, then updates positions using the new velocities.
        The updated flock is returned as a new list of ``Boid`` objects.
        
        Returns:
            list[Boid]:
                The updated flock after one simulation step.
        
        Notes:
            Each boid is updated using the current flock state and the
            universe parameters. Positions are advanced by adding the updated
            velocity to the current position.
        
        Examples:
            >>> updated_flock = universe.step()
            >>> first_boid = updated_flock[0]
            >>> first_boid.position()
        """

@typing.final
class VoiceLeading:
    r"""
    Reserved for future voice-leading path search between chords.
    """
    def __new__(cls) -> VoiceLeading: ...

@typing.final
class Voicing:
    r"""
    A specific arrangement of pitches as MIDI key numbers.
    """
    @property
    def notes(self) -> builtins.list[builtins.int]:
        r"""
        MIDI key numbers in voice order.
        """
    @property
    def all_intervals(self) -> builtins.list[builtins.int]:
        r"""
        All pairwise semitone distances between notes, sorted ascending.
        """
    @property
    def adjacent_intervals(self) -> builtins.list[builtins.int]:
        r"""
        Semitone distances between adjacent notes in voice order.
        """
    @property
    def span(self) -> builtins.int:
        r"""
        Span from lowest to highest note (semitones).
        """
    def __new__(cls, notes: typing.Sequence[builtins.int]) -> Voicing:
        r"""
        Create a voicing from an explicit list of MIDI key numbers.
        """
    def distance_to(self, other: Voicing, mode: DistanceMode = ...) -> builtins.int:
        r"""
        Distance to another voicing using the given mode.
        """

@typing.final
class DistanceMode(enum.Enum):
    r"""
    Strategy for measuring distance between two voicings.
    """
    SumAbs = ...
    r"""
    Sum of absolute semitone differences, voice by voice.
    """

@typing.final
class FitMode(enum.Enum):
    r"""
    Strategy for fitting a number into a closed interval ``[min, max]``.
    
    ``FitMode`` controls how values *outside* the interval are mapped back into it.
    If a value is already within ``[min, max]``, it is returned unchanged.
    
    Modes:
        Wrap:
            Treat the interval as a repeating cycle (periodic modulo behavior).
            Values above ``max`` wrap around to ``min``; values below ``min`` wrap
            around from the top.
    
        Reflect:
            Mirror values back into the interval by reflecting them off the nearest
            boundary (coordinate-based reflection).
    
        Bounce:
            Interpret the value as "travel energy" across the interval.
            ``num >= 0`` starts at ``min`` moving right; ``num < 0`` starts at ``max``
            moving left; the value bounces off the boundaries until the energy is spent.
    
        Clamp:
            Pin values outside the interval to the nearest boundary.
    
    Examples:
        Using the interval ``[0, 10]``:
    
        - ``Wrap``: ``15 -> 5``, ``25 -> 5``, ``-3 -> 7``
        - ``Reflect``: ``12 -> 8``, ``23 -> 3``, ``-23 -> 7``
        - ``Bounce``: ``12 -> 8``, ``23 -> 3``, ``-12 -> 2``, ``-23 -> 7``
        - ``Clamp``: ``15 -> 10``, ``-3 -> 0``
    
    Notes:
        The public ``fit`` function also handles edge cases (non-finite values and
        extremely large spans) by returning a safe in-range value.
    """
    Wrap = ...
    r"""
    **Wrap** — Treat the range as a repeating cycle. Values above the upper bound
    wrap to the lower side, and values below the lower bound wrap to the upper side.
    
    Example with range [0, 10]: 15 → 5, 25 → 5, -3 → 7.
    """
    Reflect = ...
    r"""
    **Reflect** — Values outside the range are reflected back into the interval at
    the boundaries, as if mirrored in the walls of the range, instead of wrapping.
    
    Example with range [0, 10]: 12 → 8, 23 → 3, -23 → 7.
    """
    Bounce = ...
    r"""
    **Bounce** — Interpret the value as an amount of "energy" to travel
    within the range. `num >= 0` starts at the lower bound and moves right;
    `num < 0` starts at the upper bound and moves left, bouncing off the
    bounds until all energy is spent.
    
    Example with range [0, 10]: 12 → 8, 23 → 3, -12 → 2, -23 → 7.
    """
    Clamp = ...
    r"""
    **Clamp** — Values outside the range are pinned to the nearest bound. No wrapping
    or reflection; the result is always one of the two endpoints when outside.
    
    Example with range [0, 10]: 15 → 10, -3 → 0.
    """

def bouncing_ball(height: builtins.float, velocity: builtins.float, gravity: typing.Optional[builtins.float] = None, elasticity: builtins.float = 1.0, samples_per_second: builtins.float = 100.0, max_time: typing.Optional[builtins.float] = None) -> builtins.list[tuple[builtins.float, builtins.float]]:
    r"""
    Generate a bouncing-ball curve sampled at regular time intervals.
    
    This function returns a list of ``(height, time)`` pairs describing vertical
    motion under constant gravity. When the ball hits the ground, it bounces back up with a velocity
    scaled by the `elasticity` parameter. Very small rebounds are suppressed so the ball settles to rest.
    
    Parameters:
        height (float):
            Initial height. Must be finite and ``>= 0``.
        velocity (float):
            Initial vertical velocity. Positive values move upward; negative
            values move downward. Must be finite.
        gravity (float, optional):
            Gravitational acceleration (positive). If ``None``, standard Earth
            gravity (9.80665 m/s²) is used.
        elasticity (float, default=1.0):
            Coefficient of restitution in ``[0, 1]``. Controls how much velocity
            is retained after each impact. ``1.0`` is perfectly elastic (no decay) so
            the ball would bounce without losing energy, similar to an LFO, where as
            ``0.0`` removes all energy at the first impact.
        samples_per_second (float, default=100.0):
            Sampling rate in Hz. Must be finite and ``> 0``.
        max_time (float, optional):
            Maximum duration in seconds. Must be finite and ``> 0``. If ``None``,
            a default duration is used.
    
    Returns:
        list[tuple[float, float]]:
            Samples of ``(height, time)``. Heights are guaranteed to be
            non-negative. Times increase according to the sampling rate from ``0`` up to
            ``max_time``.
    
    Raises:
        ValueError:
            If any argument is non-finite, or if any constraint is violated:
    
            - ``height < 0``
            - ``gravity <= 0``
            - ``elasticity`` not between 0 and 1 `
            - ``samples_per_second <= 0``
            - ``max_time <= 0``
    
    Notes:
        The output is computed using a semi-implicit (symplectic) Euler method.
        This produces stable, predictable curves suitable for control and
        modulation.
    
    Examples:
        Basic usage (default gravity, perfectly elastic):
    
        >>> samples = bouncing_ball(height=1.0, velocity=0.0)
    
        A decaying gesture:
    
        >>> samples = bouncing_ball(height=1.0, velocity=0.0, elasticity=0.8, max_time=3.0)
    
        Slower motion under reduced gravity:
    
        >>> samples = bouncing_ball(height=1.0, velocity=0.0, gravity=1.62, max_time=5.0)
    """

def bpm_to_seconds(bpm: builtins.float) -> builtins.float: ...

def create_boids_with_random_positions(flock_size: builtins.int, dimensions: Dimensions) -> builtins.list[Boid]:
    r"""
    Create boids with random positions inside the given dimensions.
    
    This is a convenience function for initializing a flock. Each boid is
    placed uniformly at random within the bounding box defined by
    ``dimensions`` and starts with zero velocity.
    
    Parameters:
        flock_size (int):
            Number of boids to create.
        dimensions (Dimensions):
            World bounds used to generate initial positions.
    
    Returns:
        list[Boid]:
            A list of boids with random in-bounds positions and zero velocity.
    
    Examples:
        >>> dims = Dimensions(-100.0, 100.0, -100.0, 100.0, -100.0, 100.0)
        >>> flock = create_boids_with_random_positions(10, dims)
        >>> len(flock)
        10
    """

def fit(mode: FitMode, min: builtins.float, max: builtins.float, num: builtins.float) -> builtins.float:
    r"""
    Fit a number into the closed interval ``[min, max]`` using the given mode.
    
    If ``num`` is already within ``[min, max]``, it is returned unchanged.
    Otherwise, the chosen ``mode`` determines how values outside the interval are
    mapped back into it.
    
    Args:
        mode (FitMode): The strategy used to map values into the interval.
        min (float): The lower bound of the interval.
        max (float): The upper bound of the interval.
        num (float): The value to fit into the interval.
    
    Returns:
        float: A value within ``[min, max]``.
    
    Raises:
        ValueError: If ``max - min`` is not positive (i.e., ``min >= max``).
        ValueError: If ``min`` or ``max`` are not finite.
    
    Examples:
        Using the interval ``[0, 10]``:
    
        - ``Wrap``: ``fit(Wrap, 0, 10, 12) == 2``; ``fit(Wrap, 0, 10, -4) == 6``
        - ``Reflect``: ``fit(Reflect, 0, 10, 12) == 8``; ``fit(Reflect, 0, 10, -4) == 4``
        - ``Bounce``: ``fit(Bounce, 0, 10, 12) == 8``; ``fit(Bounce, 0, 10, -12) == 2``
        - ``Clamp``: ``fit(Clamp, 0, 10, 12) == 10``; ``fit(Clamp, 0, 10, -4) == 0``
    
    Notes:
        - The interval is treated as *closed*: endpoints are included.
        - Wrap and Reflect mode will revert to Clamp mode when the range between min and
          max is not finite due to an overflow.
        - Bounce mode will revert to Clamp mode when |num| / range is not finite due
          to an overflow.
    """

def fit_list(mode: FitMode, min: builtins.float, max: builtins.float, nums: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]:
    r"""
    Fit a list of numbers into the closed interval ``[min, max]`` using the given mode.
    
    Args:
        mode (FitMode): The strategy used to map values into the interval.
        min (float): The lower bound of the interval.
        max (float): The upper bound of the interval.
        nums (list of float): The values to fit into the interval.
    
    Returns:
        list of float: The fitted values.
    
    Raises:
        ValueError: If ``min`` or ``max`` are not finite.
        ValueError: If ``max - min`` is not positive (i.e., ``min >= max``).
        ValueError: If any of the values in ``nums`` are not finite.
    """

def interval_class(interval: builtins.int) -> builtins.int:
    r"""
    Map a pitch interval (in semitones, any representative mod 12) to interval class 0–6.
    
    ``0`` means unison/octave (interval ≡ 0 mod 12); classes ``1``–``6`` are the usual
    interval classes for distinct pitch classes.
    """

def invert(pc: builtins.int) -> builtins.int:
    r"""
    Invert a pitch class around 0.
    
    This computes the inversion of a pitch class by subtracting it from 12
    and wrapping the result modulo 12.
    
    Args:
        pc (int): The pitch class to invert.
            Must be an integer in the range 0–11.
    
    Returns:
        int: The inverted pitch class, wrapped to the range 0–11.
    
    Raises:
        ValueError: If ``pc`` is not in the range 0–11.
    
    Notes:
        This function uses an i8 under the hood. While it will raise an exception
        if the input is outside the range 0–11, you will get an OverflowError results if
        the input is outside the range of an i8 (i.e. -128 to 127).
    """

def invert_ordered_set(ordered_set: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]:
    r"""
    Invert an ordered pitch-class row around 0.
    
    Each pitch class in the ordered set is inverted by subtracting it from 12
    and wrapping the result modulo 12. The order of the input row is preserved.
    
    Args:
        ordered_set (list[int]): The ordered pitch classes to invert.
            Each pitch class must be in the range 0–11.
    
    Returns:
        list[int]: The inverted ordered set, with each pitch class wrapped to
        the range 0–11.
    
    Raises:
        ValueError: If any pitch class is outside the range 0–11.
    """

def keynum_to_pitch(keynum: builtins.int) -> Pitch:
    r"""
    Build a :class:`Pitch` from a MIDI key number.
    """

def quadratic_bouncing_ball(height: builtins.float, velocity: builtins.float, gravity: typing.Optional[builtins.float] = None, elasticity: builtins.float = 1.0, samples_per_second: builtins.float = 100.0, max_time: typing.Optional[builtins.float] = None) -> builtins.list[tuple[builtins.float, builtins.float]]:
    r"""
    Simulate a bouncing ball and return sampled (height, time) points.
    
    Physics: vertical motion with gravity; at each ground impact the vertical
    velocity is multiplied by ``-elasticity`` (coefficient of restitution).
    
    Args:
        height (float): Initial height in meters (>= 0).
        velocity (float): Initial vertical velocity in m/s (positive = up).
        gravity (float | None): Gravitational acceleration in m/s²; None uses Earth default (9.80665).
        elasticity (float): Coefficient of restitution in [0, 1] (1 = perfectly elastic).
        samples_per_second (float): Sampling rate in Hz (must be > 0).
        max_time (float | None): Simulation end time in seconds; None uses default (10.0).
    
    Returns:
        list[tuple[float, float]]: List of (height, time) tuples at uniform time steps.
    
    Raises:
        ValueError: If height < 0, samples_per_second <= 0, max_time <= 0, or elasticity not in [0, 1].
    """

def quantize(step: builtins.float, value: builtins.float) -> builtins.float:
    r"""
    Quantize a value to the nearest multiple of ``step``.
    
    Returns ``round(value / step) * step`` using IEEE-754 ``f64`` rounding
    (round half away from zero).
    
    Args:
        step (float): The quantization step (grid size). Must be finite and non-zero.
        value (float): The value to quantize.
    
    Returns:
        float: The quantized value.
    
    Raises:
        ValueError: If ``step`` is zero or not finite.
        ValueError: If ``value`` is not finite.
        ValueError: If ``step`` and ``value`` are such that quantization would
            overflow ``f64``.
    
    Notes:
        For IEEE-754 ``f64``, quantization is guaranteed not to overflow when:
    
        .. math::
            |value| \le \min\bigl(\text{f64::MAX} \cdot |step|,\;
                                     \text{f64::MAX} - 0.5\cdot|step|\bigr).
    
    Examples:
        ``quantize(1.0, 2.7) == 3.0``
        ``quantize(1.0, 2.4) == 2.0``
        ``quantize(1.0, 2.5) == 3.0``
        ``quantize(0.5, -1.3) == -1.5``
        ``quantize(0.3, 1.0) == math.isclose(0.9)``
    """

def rhythm_to_seconds(num: builtins.int, den: builtins.int, bpm: builtins.float) -> builtins.float: ...

def transpose(by_semitones: builtins.int, pc: builtins.int) -> builtins.int:
    r"""
    Transpose a pitch class by a given number of semitones.
    
    The pitch class is shifted by the given number of semitones and the
    result is wrapped modulo 12.
    
    Args:
        by_semitones (int): The number of semitones to transpose by.
            Must be in the range -11 to 11.
        pc (int): The pitch class to transpose.
            Must be an integer in the range 0–11.
    
    Returns:
        int: The transposed pitch class, wrapped to the range 0–11.
    
    Raises:
        ValueError: If ``by_semitones`` is outside the range -11 to 11.
        ValueError: If ``pc`` is not in the range 0–11.
    """

def transpose_ordered_set(by_semitones: builtins.int, ordered_set: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]:
    r"""
    Transpose an ordered pitch-class row by a given number of semitones.
    
    Each pitch class in the ordered set is shifted by the given number of
    semitones, preserving the order of the input row. Results are wrapped
    modulo 12.
    
    Args:
        by_semitones (int): The number of semitones to transpose by.
            Must be in the range -11 to 11.
        ordered_set (list[int]): The ordered pitch classes to transpose.
            Each pitch class must be in the range 0–11.
    
    Returns:
        list[int]: The transposed ordered set, with each pitch class wrapped
        to the range 0–11.
    
    Raises:
        ValueError: If ``by_semitones`` is outside the range -11 to 11.
        ValueError: If any pitch class is outside the range 0–11.
    """

def voicings_from_pc_set(pcs: PitchClassSet, octave: builtins.int = 4) -> builtins.list[Voicing]:
    r"""
    Enumerate all voicings of a pitch-class set at a given register.
    
    The first pitch class in ``pcs`` (input order) is placed at ``octave``
    (default 4, e.g. C4 = MIDI 60 when that pitch class is 0). Each permutation
    of the set is realized by walking ascending pitch-class steps along the order.
    """

def voicings_from_pc_set_in_keynum_range(pcs: PitchClassSet, min_keynum: builtins.int, max_keynum: builtins.int) -> builtins.list[Voicing]:
    r"""
    Enumerate voicings whose notes all lie in ``[min_keynum, max_keynum]``.
    
    For each permutation, voices ascend by pitch-class steps along the order, with
    optional octave displacements (+12) between adjacent voices. No anchor register
    is used.
    """

def voicings_from_pc_set_within_span(pcs: PitchClassSet, max_span: builtins.int) -> builtins.list[Voicing]:
    r"""
    Enumerate voicings with span (highest minus lowest note) at most ``max_span``.
    
    Searches MIDI keynums 0–127. Uses the same voice-leading walk as
    ``voicings_from_pc_set_in_keynum_range``, without anchoring.
    """

