# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "BarlineType",
    "Boid",
    "ClefSign",
    "Dimensions",
    "DistanceMode",
    "FitMode",
    "MnxBarline",
    "MnxClef",
    "MnxDocument",
    "MnxEvent",
    "MnxGlobalData",
    "MnxKeySignature",
    "MnxMeasureGlobal",
    "MnxMetadata",
    "MnxNote",
    "MnxNoteValue",
    "MnxPart",
    "MnxPartMeasure",
    "MnxPitch",
    "MnxPositionedClef",
    "MnxRest",
    "MnxSequence",
    "MnxTempo",
    "MnxTimeSignature",
    "NoteStep",
    "NoteValueBase",
    "Pitch",
    "PitchClassSet",
    "Universe",
    "VoiceLeading",
    "Voicing",
    "bouncing_ball",
    "bpm_to_seconds",
    "create_boids_with_random_positions",
    "fit",
    "fit_list",
    "interval_class",
    "invert",
    "invert_ordered_set",
    "keynum_to_pitch",
    "quadratic_bouncing_ball",
    "quantize",
    "rhythm_to_seconds",
    "satisfy_pc",
    "transpose",
    "transpose_ordered_set",
    "voicings_from_pc_set",
    "voicings_from_pc_set_in_keynum_range",
    "voicings_from_pc_set_within_span",
]

@typing.final
class Boid:
    r"""
    Represent a single boid in the flock.
    
    A ``Boid`` stores a 3D position and a 3D velocity.
    
    Parameters:
        position (list[float]):
            Initial position as ``[x, y, z]``. Must contain exactly 3 elements.
        velocity (list[float]):
            Initial velocity as ``[vx, vy, vz]``. Must contain exactly 3 elements.
    
    Raises:
        ValueError:
            If ``position`` does not contain exactly 3 elements.
        ValueError:
            If ``velocity`` does not contain exactly 3 elements.
    
    Examples:
        >>> boid = Boid([0.0, 0.0, 0.0], [1.0, 0.0, 0.0])
        >>> boid.position()
        (0.0, 0.0, 0.0)
        >>> boid.velocity()
        (1.0, 0.0, 0.0)
    """
    def __new__(cls, position: typing.Sequence[builtins.float], velocity: typing.Sequence[builtins.float]) -> Boid: ...
    def position(self) -> tuple[builtins.float, builtins.float, builtins.float]:
        r"""
        Return the boid position as ``(x, y, z)``.
        
        Returns:
            tuple[float, float, float]:
                The current position.
        """
    def velocity(self) -> tuple[builtins.float, builtins.float, builtins.float]:
        r"""
        Return the boid velocity as ``(vx, vy, vz)``.
        
        Returns:
            tuple[float, float, float]:
                The current velocity.
        """

@typing.final
class Dimensions:
    r"""
    ``Dimensions`` describes the axis-bounded bounding box that contains the
    flock. The bounds are used by ``Universe`` to steer boids back toward the
    interior when they move outside coordinates.
    
    Parameters:
        x_min (float):
            Minimum x coordinate.
        x_max (float):
            Maximum x coordinate.
        y_min (float):
            Minimum y coordinate.
        y_max (float):
            Maximum y coordinate.
        z_min (float):
            Minimum z coordinate.
        z_max (float):
            Maximum z coordinate.
    
    Attributes:
        x_min (float):
            Minimum x coordinate.
        x_max (float):
            Maximum x coordinate.
        y_min (float):
            Minimum y coordinate.
        y_max (float):
            Maximum y coordinate.
        z_min (float):
            Minimum z coordinate.
        z_max (float):
            Maximum z coordinate.
    
    Raises:
        ValueError: If any minimum is greater than or equal to its maximum
        (e.g. x_min >= x_max).
    
    Examples:
        >>> dims = Dimensions(-500.0, 500.0, -500.0, 500.0, -500.0, 500.0)
    """
    @property
    def x_min(self) -> builtins.float: ...
    @x_min.setter
    def x_min(self, value: builtins.float) -> None: ...
    @property
    def x_max(self) -> builtins.float: ...
    @x_max.setter
    def x_max(self, value: builtins.float) -> None: ...
    @property
    def y_min(self) -> builtins.float: ...
    @y_min.setter
    def y_min(self, value: builtins.float) -> None: ...
    @property
    def y_max(self) -> builtins.float: ...
    @y_max.setter
    def y_max(self, value: builtins.float) -> None: ...
    @property
    def z_min(self) -> builtins.float: ...
    @z_min.setter
    def z_min(self, value: builtins.float) -> None: ...
    @property
    def z_max(self) -> builtins.float: ...
    @z_max.setter
    def z_max(self, value: builtins.float) -> None: ...
    def __new__(cls, x_min: builtins.float, x_max: builtins.float, y_min: builtins.float, y_max: builtins.float, z_min: builtins.float, z_max: builtins.float) -> Dimensions: ...

@typing.final
class MnxBarline:
    r"""
    A barline drawn at the end of a measure.
    
    If omitted from a measure, consuming software infers ``Regular`` for all
    measures except the last, which defaults to ``Final``.
    """
    @property
    def kind(self) -> BarlineType:
        r"""
        The visual style of this barline.
        """
    def __new__(cls, kind: BarlineType) -> MnxBarline:
        r"""
        Create a barline.
        
        Args:
            kind (BarlineType): The visual style of the barline.
        
        Returns:
            MnxBarline
        """

@typing.final
class MnxClef:
    r"""
    A clef definition: sign, staff line position, and optional octave transposition.
    
    The ``staff_position`` follows MNX convention: a standard G clef is drawn
    at position ``-2`` (the second line from the bottom).
    """
    @property
    def sign(self) -> ClefSign:
        r"""
        The clef sign.
        """
    @property
    def staff_position(self) -> builtins.int:
        r"""
        The staff position at which the clef glyph is drawn.
        """
    def __new__(cls, sign: ClefSign, staff_position: builtins.int) -> MnxClef:
        r"""
        Create a clef.
        
        Args:
            sign (ClefSign): The clef sign (G, F, C, …).
            staff_position (int): Staff position at which the clef glyph is drawn.
                A standard treble clef uses ``-2``. A standard bass clef uses ``2``.
        
        Returns:
            MnxClef
        """

@typing.final
class MnxDocument:
    r"""
    The root MNX document object.
    
    An ``MnxDocument`` contains everything needed to represent a complete piece
    of music: metadata, global measure data (time/key signatures, tempos), and
    one or more parts.
    
    Use :meth:`to_json` or :meth:`to_json_pretty` to produce MNX-compliant JSON.
    Use :meth:`from_json` to parse an existing MNX JSON string.
    
    Examples:
        Hello world — C4 whole note, 4/4, treble clef::
    
            from allegro.mnx import (
                MnxDocument, MnxMetadata, MnxGlobalData, MnxMeasureGlobal,
                MnxPart, MnxPartMeasure, MnxSequence, MnxEvent,
                MnxNote, MnxPitch, MnxNoteValue, MnxClef, MnxPositionedClef,
                MnxKeySignature, MnxTimeSignature,
                NoteStep, NoteValueBase, ClefSign,
            )
    
            doc = MnxDocument(
                mnx=MnxMetadata(version=1),
                global_data=MnxGlobalData(measures=[
                    MnxMeasureGlobal(
                        time=MnxTimeSignature(count=4, unit=4),
                        key=MnxKeySignature(fifths=0),
                    )
                ]),
                parts=[MnxPart(measures=[
                    MnxPartMeasure(
                        clefs=[MnxPositionedClef(clef=MnxClef(
                            sign=ClefSign.G, staff_position=-2
                        ))],
                        sequences=[MnxSequence(content=[
                        sequences=[MnxSequence(content=[
                            MnxEvent.note(
                                duration=MnxNoteValue(base=NoteValueBase.Whole),
                                notes=[MnxNote(pitch=MnxPitch(
                                    step=NoteStep.C, octave=4
                                ))],
                            )
                        ])],
                    )
                ])],
            )
            print(doc.to_json_pretty())
    """
    @property
    def mnx(self) -> MnxMetadata:
        r"""
        The MNX metadata (version, etc.).
        """
    @property
    def global_data(self) -> MnxGlobalData:
        r"""
        The global measure data.
        """
    @property
    def parts(self) -> builtins.list[MnxPart]:
        r"""
        The instrument parts.
        """
    def __new__(cls, mnx: MnxMetadata, global_data: MnxGlobalData, parts: typing.Sequence[MnxPart]) -> MnxDocument:
        r"""
        Create an MNX document.
        
        Args:
            mnx (MnxMetadata): Document metadata (includes the MNX version).
            global_data (MnxGlobalData): Global measure data shared across all
                parts (time/key signatures, tempos, barlines).
            parts (list[MnxPart]): One or more instrument parts. Every part
                must contain the same number of measures as ``global_data``.
        
        Returns:
            MnxDocument
        """
    def to_json(self) -> builtins.str:
        r"""
        Serialize this document to a compact MNX JSON string.
        
        Returns:
            str: A compact JSON representation of this MNX document.
        """
    def to_json_pretty(self) -> builtins.str:
        r"""
        Serialize this document to a pretty-printed MNX JSON string.
        
        Returns:
            str: An indented JSON representation of this MNX document.
        """
    @staticmethod
    def from_json(json: builtins.str) -> MnxDocument:
        r"""
        Parse an MNX JSON string into an :class:`MnxDocument`.
        
        Args:
            json (str): A valid MNX JSON string.
        
        Returns:
            MnxDocument
        
        Raises:
            ValueError: If the JSON is malformed or does not match the MNX schema.
        """

@typing.final
class MnxEvent:
    r"""
    A discrete musical event: a set of simultaneous pitched notes, or a rest.
    
    Construct via the named factory methods rather than directly:
    
    - :meth:`MnxEvent.note` — one or more simultaneous pitches (chord or single note)
    - :meth:`MnxEvent.rest` — a silent rest
    
    This design makes intent unambiguous at the call site and eliminates
    invalid states (neither notes nor rest; both notes and rest).
    
    Extension note: when tuplet and grace-note sequence items are added they
    will implement a shared ``SequenceItem`` trait alongside ``MnxEvent``.
    """
    @property
    def duration(self) -> MnxNoteValue:
        r"""
        The rhythmic duration of this event.
        """
    @property
    def notes(self) -> typing.Optional[builtins.list[MnxNote]]:
        r"""
        Notes sounding in this event, or ``None`` if this is a rest.
        """
    @property
    def is_rest(self) -> builtins.bool:
        r"""
        ``True`` if this event is a rest; ``False`` if it contains notes.
        """
    @staticmethod
    def note(duration: MnxNoteValue, notes: typing.Sequence[MnxNote]) -> MnxEvent:
        r"""
        Create a note event containing one or more simultaneous pitches.
        
        A single-element list produces a single note; multiple elements produce
        a chord.
        
        Args:
            duration (MnxNoteValue): The rhythmic duration.
            notes (list[MnxNote]): One or more notes sounding together.
        
        Returns:
            MnxEvent
        
        Examples:
            Single note::
        
                event = MnxEvent.note(
                    duration=MnxNoteValue(base=NoteValueBase.Quarter),
                    notes=[MnxNote(pitch=MnxPitch(step=NoteStep.C, octave=4))],
                )
        
            Chord::
        
                event = MnxEvent.note(
                    duration=MnxNoteValue(base=NoteValueBase.Half),
                    notes=[
                        MnxNote(pitch=MnxPitch(step=NoteStep.C, octave=4)),
                        MnxNote(pitch=MnxPitch(step=NoteStep.E, octave=4)),
                        MnxNote(pitch=MnxPitch(step=NoteStep.G, octave=4)),
                    ],
                )
        """
    @staticmethod
    def rest(duration: MnxNoteValue) -> MnxEvent:
        r"""
        Create a rest event.
        
        Args:
            duration (MnxNoteValue): The rhythmic duration of the rest.
        
        Returns:
            MnxEvent
        
        Examples:
            Whole-note rest::
        
                event = MnxEvent.rest(duration=MnxNoteValue(base=NoteValueBase.Whole))
        """

@typing.final
class MnxGlobalData:
    r"""
    The global section of an MNX document: one ``MnxMeasureGlobal`` per measure.
    """
    @property
    def measures(self) -> builtins.list[MnxMeasureGlobal]:
        r"""
        The list of per-measure global metadata objects.
        """
    def __new__(cls, measures: typing.Sequence[MnxMeasureGlobal]) -> MnxGlobalData:
        r"""
        Create the global data section.
        
        Args:
            measures (list[MnxMeasureGlobal]): One entry per measure in the
                document. Every part must have the same number of measures.
        
        Returns:
            MnxGlobalData
        """

@typing.final
class MnxKeySignature:
    r"""
    A key signature defined by its distance in fifths from C major / A minor.
    
    Positive values indicate sharps; negative values indicate flats.
    Zero indicates C major / A minor (no accidentals).
    
    Examples:
        G major (1 sharp): ``MnxKeySignature(fifths=1)``
    
        F major (1 flat): ``MnxKeySignature(fifths=-1)``
    """
    @property
    def fifths(self) -> builtins.int:
        r"""
        Distance in fifths from C major / A minor.
        """
    def __new__(cls, fifths: builtins.int) -> MnxKeySignature:
        r"""
        Create a key signature.
        
        Args:
            fifths (int): Distance in perfect fifths from C (positive = sharps,
                negative = flats).
        
        Returns:
            MnxKeySignature
        """

@typing.final
class MnxMeasureGlobal:
    r"""
    Global measure metadata shared across all parts.
    
    Each ``MnxMeasureGlobal`` corresponds to one measure in every part.
    Only attributes that change need to appear; omitted attributes are
    inherited from the previous measure or left to the consuming application.
    """
    @property
    def time(self) -> typing.Optional[MnxTimeSignature]:
        r"""
        The time signature for this measure, if set.
        """
    @property
    def key(self) -> typing.Optional[MnxKeySignature]:
        r"""
        The key signature for this measure, if set.
        """
    @property
    def barline(self) -> typing.Optional[MnxBarline]:
        r"""
        The barline at the end of this measure, if set.
        """
    @property
    def tempos(self) -> typing.Optional[builtins.list[MnxTempo]]:
        r"""
        Tempo markings at the start of this measure, if any.
        """
    def __new__(cls, time: typing.Optional[MnxTimeSignature] = None, key: typing.Optional[MnxKeySignature] = None, barline: typing.Optional[MnxBarline] = None, tempos: typing.Optional[typing.Sequence[MnxTempo]] = None) -> MnxMeasureGlobal:
        r"""
        Create global measure metadata.
        
        Args:
            time (MnxTimeSignature | None): Time signature. Supply only in the
                first measure or when it changes.
            key (MnxKeySignature | None): Key signature. Supply only in the
                first measure or when it changes.
            barline (MnxBarline | None): Barline at the end of this measure.
            tempos (list[MnxTempo] | None): Tempo markings at the start of
                this measure.
        
        Returns:
            MnxMeasureGlobal
        """

@typing.final
class MnxMetadata:
    r"""
    MNX document metadata: currently just the format version number.
    """
    @property
    def version(self) -> builtins.int:
        r"""
        The MNX version number.
        """
    def __new__(cls, version: builtins.int) -> MnxMetadata:
        r"""
        Create MNX metadata.
        
        Args:
            version (int): The MNX version number (use ``1`` for the current draft).
        
        Returns:
            MnxMetadata
        """

@typing.final
class MnxNote:
    r"""
    A single note within an event, identified by its sounded pitch.
    
    Future attributes (ties, staff override, accidental display) can be added
    without breaking existing documents.
    """
    @property
    def pitch(self) -> MnxPitch:
        r"""
        The sounded pitch of this note.
        """
    def __new__(cls, pitch: MnxPitch) -> MnxNote:
        r"""
        Create a note.
        
        Args:
            pitch (MnxPitch): The sounded pitch of this note.
        
        Returns:
            MnxNote
        """

@typing.final
class MnxNoteValue:
    r"""
    A rhythmic note value: a base duration plus optional augmentation dots.
    
    Examples:
        A dotted quarter note: ``MnxNoteValue(base=NoteValueBase.Quarter, dots=1)``
    
        A whole note: ``MnxNoteValue(base=NoteValueBase.Whole)``
    """
    @property
    def base(self) -> NoteValueBase:
        r"""
        The base rhythmic duration.
        """
    @property
    def dots(self) -> typing.Optional[builtins.int]:
        r"""
        Number of augmentation dots, if any.
        """
    def __new__(cls, base: NoteValueBase, dots: typing.Optional[builtins.int] = None) -> MnxNoteValue:
        r"""
        Create a new note value.
        
        Args:
            base (NoteValueBase): The base rhythmic duration.
            dots (int | None): Number of augmentation dots (0–5). Defaults to ``None``.
        
        Returns:
            MnxNoteValue
        """

@typing.final
class MnxPart:
    r"""
    A single instrument part containing one measure per global measure.
    """
    @property
    def measures(self) -> builtins.list[MnxPartMeasure]:
        r"""
        The measures of this part.
        """
    @property
    def name(self) -> typing.Optional[builtins.str]:
        r"""
        The display name of this part, if set.
        """
    @property
    def staves(self) -> typing.Optional[builtins.int]:
        r"""
        The number of staves in this part, if set.
        """
    def __new__(cls, measures: typing.Sequence[MnxPartMeasure], name: typing.Optional[builtins.str] = None, staves: typing.Optional[builtins.int] = None) -> MnxPart:
        r"""
        Create a part.
        
        Args:
            measures (list[MnxPartMeasure]): One measure per global measure.
                The length must match ``MnxGlobalData.measures``.
            name (str | None): Display name for the part (e.g. ``"Violin I"``).
            staves (int | None): Number of staves (default ``1``; use ``2`` for
                grand staff as in piano music).
        
        Returns:
            MnxPart
        """

@typing.final
class MnxPartMeasure:
    r"""
    A single measure within a part, containing sequences of events and optional clef changes.
    """
    @property
    def sequences(self) -> builtins.list[MnxSequence]:
        r"""
        The sequences (voices) in this measure.
        """
    @property
    def clefs(self) -> typing.Optional[builtins.list[MnxPositionedClef]]:
        r"""
        Clef changes in this measure, if any.
        """
    def __new__(cls, sequences: typing.Sequence[MnxSequence], clefs: typing.Optional[typing.Sequence[MnxPositionedClef]] = None) -> MnxPartMeasure:
        r"""
        Create a part measure.
        
        Args:
            sequences (list[MnxSequence]): One sequence per voice. A typical
                single-voice measure has exactly one sequence.
            clefs (list[MnxPositionedClef] | None): Clef changes within this
                measure. A clef at the start of the first measure sets the initial
                clef for the part.
        
        Returns:
            MnxPartMeasure
        """

@typing.final
class MnxPitch:
    r"""
    The sounded pitch of a note: step, octave, and optional chromatic alteration.
    
    Pitches are represented using the diatonic step (C–G), a Helmholtz octave
    number (4 = middle C octave), and an optional ``alter`` value in semitones
    (e.g. ``1.0`` for sharp, ``-1.0`` for flat).
    """
    @property
    def step(self) -> NoteStep:
        r"""
        The diatonic pitch step.
        """
    @property
    def octave(self) -> builtins.int:
        r"""
        The octave number (4 = middle C octave).
        """
    @property
    def alter(self) -> typing.Optional[builtins.float]:
        r"""
        Chromatic alteration in semitones, if any.
        """
    def __new__(cls, step: NoteStep, octave: builtins.int, alter: typing.Optional[builtins.float] = None) -> MnxPitch:
        r"""
        Create a new pitch.
        
        Args:
            step (NoteStep): The diatonic pitch step (A–G).
            octave (int): The octave number (4 = middle C octave).
            alter (float | None): Chromatic alteration in semitones
                (``1.0`` for sharp, ``-1.0`` for flat). Defaults to ``None``.
        
        Returns:
            MnxPitch
        """

@typing.final
class MnxPositionedClef:
    r"""
    A clef placed at a specific position within a measure.
    
    If no ``position`` is supplied the clef is assumed to be at the start of
    the measure.
    """
    @property
    def clef(self) -> MnxClef:
        r"""
        The clef definition.
        """
    def __new__(cls, clef: MnxClef) -> MnxPositionedClef:
        r"""
        Create a positioned clef.
        
        Args:
            clef (MnxClef): The clef definition.
        
        Returns:
            MnxPositionedClef
        """

@typing.final
class MnxRest:
    r"""
    A rest within an event. Serializes as an empty object ``{}``.
    """
    def __new__(cls) -> MnxRest:
        r"""
        Create a rest.
        
        Returns:
            MnxRest
        """

@typing.final
class MnxSequence:
    r"""
    An ordered sequence of events forming a single polyphonic voice within a measure.
    
    All events in a sequence must cover the full duration of the measure
    when summed. Use the ``voice`` attribute to distinguish multiple sequences
    (voices) within the same measure.
    """
    @property
    def content(self) -> builtins.list[MnxEvent]:
        r"""
        The ordered events in this voice.
        """
    @property
    def voice(self) -> typing.Optional[builtins.str]:
        r"""
        The voice identifier, if any.
        """
    def __new__(cls, content: typing.Sequence[MnxEvent], voice: typing.Optional[builtins.str] = None) -> MnxSequence:
        r"""
        Create a sequence.
        
        Args:
            content (list[MnxEvent]): The ordered events in this voice.
            voice (str | None): An opaque identifier for this voice. Sequences
                sharing the same ``voice`` value across measures belong to the
                same voice. Defaults to ``None``.
        
        Returns:
            MnxSequence
        """

@typing.final
class MnxTempo:
    r"""
    A tempo marking expressed as beats-per-minute for a given note value.
    
    Examples:
        Quarter note = 120 bpm: ``MnxTempo(bpm=120.0, value=MnxNoteValue(base=NoteValueBase.Quarter))``
    """
    @property
    def bpm(self) -> builtins.float:
        r"""
        Beats per minute.
        """
    @property
    def value(self) -> MnxNoteValue:
        r"""
        The note value that receives one beat.
        """
    def __new__(cls, bpm: builtins.float, value: MnxNoteValue) -> MnxTempo:
        r"""
        Create a tempo marking.
        
        Args:
            bpm (float): Beats per minute.
            value (MnxNoteValue): The note value that receives one beat.
        
        Returns:
            MnxTempo
        """

@typing.final
class MnxTimeSignature:
    r"""
    A time signature expressed as beat count over beat unit.
    
    Examples:
        4/4 time: ``MnxTimeSignature(count=4, unit=4)``
    
        6/8 time: ``MnxTimeSignature(count=6, unit=8)``
    """
    @property
    def count(self) -> builtins.int:
        r"""
        The beat count (top number of the time signature).
        """
    @property
    def unit(self) -> builtins.int:
        r"""
        The beat unit (bottom number of the time signature).
        """
    def __new__(cls, count: builtins.int, unit: builtins.int) -> MnxTimeSignature:
        r"""
        Create a time signature.
        
        Args:
            count (int): Number of beats (top number).
            unit (int): Beat unit as a power of two (bottom number, e.g. 4 or 8).
        
        Returns:
            MnxTimeSignature
        """

@typing.final
class Pitch:
    r"""
    A concrete pitch identified by a MIDI key number.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Scientific pitch notation (e.g. ``'C4'`` for MIDI key number 60).
        """
    @property
    def keynum(self) -> builtins.int:
        r"""
        MIDI key number for this pitch.
        """

@typing.final
class PitchClassSet:
    r"""
    A collection of distinct pitch classes.
    
    `PitchClassSet` represents a collection of distinct pitch classes,
    where each pitch class must be unique and in the range 0–11.
    
    Notes:
        Although this type represents an unordered set, the current input order
        is preserved internally. Methods that require sorted pitch classes sort
        internally before computing their results.
    """
    @property
    def pitch_classes(self) -> builtins.list[builtins.int]:
        r"""
        Get the pitch classes in this set.
        
        The returned list contains the pitch classes currently stored by the set.
        Values are represented as integers modulo 12, where 0 is C, 1 is C♯/D♭,
        and so on.
        
        Returns:
            list[int]: The pitch classes in the set.
        
        Example:
            >>> pcs.pitch_classes
            [0, 2, 4, 7]
        """
    @property
    def normal_form(self) -> builtins.list[builtins.int]:
        r"""
        Compute the normal form of the pitch-class set.
        
        The normal form is the most "compact" ordering of the set when treated as
        an ascending scale within a single octave.
        
        Algorithm:
            1. Generate all cyclic rotations of the sorted pitch classes. Each
               rotation is interpreted as an ascending pitch sequence (wrapping
               earlier elements up an octave).
        
            2. Select the rotation(s) with the smallest total span:
               (last_pitch - first_pitch).
        
            3. If multiple candidates remain, break ties by comparing intervals
               from the left:
                   - Then (second-to-last - first), if still tied,
                   - Then (third-to-last - first), and so on
               Keep only the most "left-packed" (most compact toward the beginning).
        
            4. If a tie still remains, choose the ordering whose first pitch class
               is smallest.
        
            5. Finally, wrap all pitches modulo 12 to return pitch classes.
        
        Returns:
            list[int]: The normal form of the set as pitch classes in the range 0–11.
        
        Notes:
            This implementation follows the standard post-tonal theory definition
            (Rahn/Straus style) and corresponds to the algorithm described in
            `src/specs/pitchclass.md`.
        """
    @property
    def prime_form(self) -> builtins.list[builtins.int]:
        r"""
        Compute the Rahn prime form of the pitch-class set.
        
        This computes the normal form of the set, then transposes it so that it
        begins on 0. For asymmetrical sets, this preserves the orientation of
        the set (as in the Wikipedia/Forte A/B columns) rather than collapsing
        inversionally related forms to a single Rahn lexicographic minimum.
        
        Returns:
            list[int]: The prime form of the set as pitch classes in the range 0–11.
        """
    @property
    def forte_num(self) -> builtins.str:
        r"""
        Look up the Forte number for the pitch-class set.
        
        The set is converted to its oriented Rahn prime form (normal form T0,
        preserving inversional orientation) and then matched against the Forte
        catalog (Wikipedia/Rahn prime column, including A/B variants).
        
        Returns:
            str: The Forte number for the set.
        
        Raises:
            ValueError: If the prime form is not found in the Forte catalog.
        """
    @property
    def interval_vector(self) -> builtins.list[builtins.int]:
        r"""
        Compute the Forte interval-class vector for this pitch-class set.
        
        The interval-class vector is a six-element count of the unordered pitch-class
        intervals present in the set. For each unordered pair of distinct pitch
        classes, the smaller directed interval is computed modulo 12, mapped to an
        interval class from 1 through 6, and counted at index `ic - 1`.
        
        Returns:
            list[int]: The interval vector of a pitch-class set, where each position
            corresponds to interval classes 1 through 6.
        
        Example:
            >>> pcs.interval_vector
            [0, 0, 1, 1, 1, 0]
        """
    def __new__(cls, pitch_classes: typing.Sequence[builtins.int]) -> PitchClassSet:
        r"""
        Create a new pitch-class set.
        
        Args:
            pitch_classes (list[int]): The pitch classes in the set.
                Each value must be unique and in the range 0–11.
                At most 12 pitch classes are allowed.
        
        Returns:
            PitchClassSet: A new pitch-class set.
        
        Raises:
            ValueError: If more than 12 pitch classes are provided.
            ValueError: If any pitch class is duplicated.
            ValueError: If any pitch class is outside the range 0–11.
        """
    def subsets(self, min_size: builtins.int = 0) -> builtins.list[PitchClassSet]:
        r"""
        Generate all subsets of the pitch-class set.
        
        Args:
            min_size (int, optional): Only include subsets with at least this many pitch classes.
                Defaults to ``0`` (full powerset). Any value greater than the number of pitch classes
                in the set will return an empty list.
        
        Throws:
            OverflowError: If ``min_size`` is negative.
        
        Returns:
            list[PitchClassSet]: Subsets of the pitch-class set whose length is at least ``min_size``.
        """
    def count_common_tones_under_tn(self, tn: builtins.int) -> builtins.int:
        r"""
        Count how many pitch classes are shared between this set and its transposition by ``tn``
        semitones (``Tn``, mod 12).
        
        For ``tn ≡ 0 (mod 12)``, no pitches change, so the count is the cardinality
        of the set.
        
        Otherwise the we use the values in the set's interval-class vector and look up the value
        according to the interval class of tn.
        
        For example, if tn is 10, then the interval class is 2, so we look up the
        value at index ``1`` in the interval-class vector (i.e. ``iv[1]``).
        (It's at index 1, because we don't store interval class 0 in the interval-class vector.)
        
        Under **tritone** transposition, i.e. ``Tn6``, common tones are **twice** the entry in
        the interval-class vector.
        See Open Music Theory, "Common Tones under Transposition"
        (<https://openmusictheory.github.io/commonTonesUnderTransposition.html>).
        
        Args:
            tn (int): Transposition level in semitones (any integer -128..=127; reduced mod 12).
        
        Returns:
            int: Number of common pitch classes between pitch-class set and its transposition by ``tn``.
        """
    def transpose_by(self, tn: builtins.int) -> PitchClassSet:
        r"""
        Transpose the pitch-class set by a given number of semitones.
        
        The pitch-class set is transposed by the given number of semitones and the
        result is wrapped modulo 12.
        
        Args:
            tn (int): The number of semitones to transpose by.
                Must be in the range -11 to 11.
        
        Returns:
            PitchClassSet: The transposed pitch-class set.
        
        Raises:
            ValueError: If ``tn`` is outside the range -11 to 11.
        
        Example:
            >>> pcs.transpose_by(1)
            PitchClassSet([1, 3, 5, 8])
        """
    def complement(self) -> PitchClassSet:
        r"""
        Return the chromatic complement of this pitch-class set.
        
        The complement contains every pitch class in the range 0–11 that is not
        in this set. The result is returned in ascending order.
        
        Returns:
            PitchClassSet: The complement within the twelve pitch classes.
        
        Example:
            >>> PitchClassSet([0, 1, 2, 3]).complement().forte_num
            '8-1'
        """

@typing.final
class Universe:
    r"""
    Represent a boids simulation and its rule parameters.
    
    ``Universe`` stores the flock, the world bounds, and the parameters that
    control cohesion, separation, alignment, boundary steering, and optional
    speed limiting.
    
    Call ``step()`` to advance the simulation by one discrete time step.
    
    Parameters:
        flock (list[Boid]):
            Initial flock of boids.
        dimensions (Dimensions):
            World bounds for the simulation.
        cohesion_factor (float):
            Strength of cohesion. Higher values pull boids more strongly toward
            the perceived center of mass of the flock.
        separation_distance (float):
            Distance threshold used for separation. Boids closer than this
            distance push away from one another.
        alignment_factor (float):
            Strength of alignment. Higher values steer boids more strongly
            toward the perceived average flock velocity.
        bound_steer (float):
            Fixed steering amount applied when a boid crosses a world boundary.
        speed_limit (float, optional):
            Maximum allowed speed magnitude. If ``None``, no speed limit is
            applied.
    
    Notes:
        The simulation applies the following updates in order:
    
        1. Fly towards perceived center of mass
        2. Move away from close by objects
        3. Match perceived speed of flock
        4. Bound position
        5. Limit velocity
        6. Update position
    
    Examples:
        >>> dims = Dimensions(-500.0, 500.0, -500.0, 500.0, -500.0, 500.0)
        >>> flock = [Boid([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]), Boid([100.0, 0.0, 0.0], [0.0, 0.0, 0.0])]
        >>> universe = Universe(
        ...     flock,
        ...     dims,
        ...     cohesion_factor=0.01,
        ...     separation_distance=100.0,
        ...     alignment_factor=0.125,
        ...     bound_steer=10.0,
        ...     speed_limit=10.0,
        ... )
    """
    def __new__(cls, flock: typing.Sequence[Boid], dimensions: Dimensions, cohesion_factor: builtins.float, separation_distance: builtins.float, alignment_factor: builtins.float, bound_steer: builtins.float, speed_limit: typing.Optional[builtins.float] = None) -> Universe: ...
    def step(self) -> builtins.list[Boid]:
        r"""
        Advance the flock by one time step.
        
        This method applies the boids rules to every boid in the universe,
        updates velocities, then updates positions using the new velocities.
        The updated flock is returned as a new list of ``Boid`` objects.
        
        Returns:
            list[Boid]:
                The updated flock after one simulation step.
        
        Notes:
            Each boid is updated using the current flock state and the
            universe parameters. Positions are advanced by adding the updated
            velocity to the current position.
        
        Examples:
            >>> updated_flock = universe.step()
            >>> first_boid = updated_flock[0]
            >>> first_boid.position()
        """

@typing.final
class VoiceLeading:
    r"""
    Reserved for future voice-leading path search between chords.
    """
    def __new__(cls) -> VoiceLeading: ...

@typing.final
class Voicing:
    r"""
    A specific arrangement of pitches as MIDI key numbers.
    """
    @property
    def notes(self) -> builtins.list[builtins.int]:
        r"""
        MIDI key numbers in voice order.
        """
    @property
    def all_intervals(self) -> builtins.list[builtins.int]:
        r"""
        All pairwise semitone distances between notes, sorted ascending.
        """
    @property
    def adjacent_intervals(self) -> builtins.list[builtins.int]:
        r"""
        Semitone distances between adjacent notes in voice order.
        """
    @property
    def span(self) -> builtins.int:
        r"""
        Span from lowest to highest note (semitones).
        """
    def __new__(cls, notes: typing.Sequence[builtins.int]) -> Voicing:
        r"""
        Create a voicing from an explicit list of MIDI key numbers.
        """
    def distance_to(self, other: Voicing, mode: DistanceMode = ...) -> builtins.int:
        r"""
        Distance to another voicing using the given mode.
        """

@typing.final
class BarlineType(enum.Enum):
    r"""
    The visual style of a barline.
    """
    Regular = ...
    r"""
    Standard single barline.
    """
    Final = ...
    r"""
    Final double barline (thin-thick).
    """
    Double = ...
    r"""
    Double barline (thin-thin).
    """
    Dashed = ...
    r"""
    Dashed barline.
    """
    Dotted = ...
    r"""
    Dotted barline.
    """
    Tick = ...
    r"""
    Tick barline.
    """
    Short = ...
    r"""
    Short barline.
    """

@typing.final
class ClefSign(enum.Enum):
    r"""
    The sign used for a clef.
    """
    G = ...
    r"""
    Treble (G) clef.
    """
    F = ...
    r"""
    Bass (F) clef.
    """
    C = ...
    r"""
    Alto/tenor (C) clef.
    """
    Percussion = ...
    r"""
    Percussion clef.
    """
    Tab = ...
    r"""
    Tab clef (for guitar tablature).
    """

@typing.final
class DistanceMode(enum.Enum):
    r"""
    Strategy for measuring distance between two voicings.
    """
    SumAbs = ...
    r"""
    Sum of absolute semitone differences, voice by voice.
    """

@typing.final
class FitMode(enum.Enum):
    r"""
    Strategy for fitting a number into a closed interval ``[min, max]``.
    
    ``FitMode`` controls how values *outside* the interval are mapped back into it.
    If a value is already within ``[min, max]``, it is returned unchanged.
    
    Modes:
        Wrap:
            Treat the interval as a repeating cycle (periodic modulo behavior).
            Values above ``max`` wrap around to ``min``; values below ``min`` wrap
            around from the top.
    
        Reflect:
            Mirror values back into the interval by reflecting them off the nearest
            boundary (coordinate-based reflection).
    
        Bounce:
            Interpret the value as "travel energy" across the interval.
            ``num >= 0`` starts at ``min`` moving right; ``num < 0`` starts at ``max``
            moving left; the value bounces off the boundaries until the energy is spent.
    
        Clamp:
            Pin values outside the interval to the nearest boundary.
    
    Examples:
        Using the interval ``[0, 10]``:
    
        - ``Wrap``: ``15 -> 5``, ``25 -> 5``, ``-3 -> 7``
        - ``Reflect``: ``12 -> 8``, ``23 -> 3``, ``-23 -> 7``
        - ``Bounce``: ``12 -> 8``, ``23 -> 3``, ``-12 -> 2``, ``-23 -> 7``
        - ``Clamp``: ``15 -> 10``, ``-3 -> 0``
    
    Notes:
        The public ``fit`` function also handles edge cases (non-finite values and
        extremely large spans) by returning a safe in-range value.
    """
    Wrap = ...
    r"""
    **Wrap** — Treat the range as a repeating cycle. Values above the upper bound
    wrap to the lower side, and values below the lower bound wrap to the upper side.
    
    Example with range [0, 10]: 15 → 5, 25 → 5, -3 → 7.
    """
    Reflect = ...
    r"""
    **Reflect** — Values outside the range are reflected back into the interval at
    the boundaries, as if mirrored in the walls of the range, instead of wrapping.
    
    Example with range [0, 10]: 12 → 8, 23 → 3, -23 → 7.
    """
    Bounce = ...
    r"""
    **Bounce** — Interpret the value as an amount of "energy" to travel
    within the range. `num >= 0` starts at the lower bound and moves right;
    `num < 0` starts at the upper bound and moves left, bouncing off the
    bounds until all energy is spent.
    
    Example with range [0, 10]: 12 → 8, 23 → 3, -12 → 2, -23 → 7.
    """
    Clamp = ...
    r"""
    **Clamp** — Values outside the range are pinned to the nearest bound. No wrapping
    or reflection; the result is always one of the two endpoints when outside.
    
    Example with range [0, 10]: 15 → 10, -3 → 0.
    """

@typing.final
class NoteStep(enum.Enum):
    r"""
    The diatonic pitch step (letter name) of a note.
    """
    A = ...
    r"""
    The note A.
    """
    B = ...
    r"""
    The note B.
    """
    C = ...
    r"""
    The note C.
    """
    D = ...
    r"""
    The note D.
    """
    E = ...
    r"""
    The note E.
    """
    F = ...
    r"""
    The note F.
    """
    G = ...
    r"""
    The note G.
    """

@typing.final
class NoteValueBase(enum.Enum):
    r"""
    The base rhythmic duration of a note, without augmentation dots.
    """
    Maxima = ...
    r"""
    Maxima (8 whole notes).
    """
    Longa = ...
    r"""
    Longa (4 whole notes).
    """
    DuplexMaxima = ...
    r"""
    Duplex Maxima (16 whole notes).
    """
    Breve = ...
    r"""
    Breve (2 whole notes).
    """
    Whole = ...
    r"""
    Whole note.
    """
    Half = ...
    r"""
    Half note.
    """
    Quarter = ...
    r"""
    Quarter note.
    """
    Eighth = ...
    r"""
    Eighth note.
    """
    Sixteenth = ...
    r"""
    16th note.
    """
    ThirtySecond = ...
    r"""
    32nd note.
    """
    SixtyFourth = ...
    r"""
    64th note.
    """
    OneTwentyEighth = ...
    r"""
    128th note.
    """
    TwoFiftySixth = ...
    r"""
    256th note.
    """
    FiveTwelfth = ...
    r"""
    512th note.
    """
    TenTwentyFourth = ...
    r"""
    1024th note.
    """
    TwoThousandFortyEighth = ...
    r"""
    2048th note.
    """
    FourThousandNinetySixth = ...
    r"""
    4096th note.
    """

def bouncing_ball(height: builtins.float, velocity: builtins.float, gravity: typing.Optional[builtins.float] = None, elasticity: builtins.float = 1.0, samples_per_second: builtins.float = 100.0, max_time: typing.Optional[builtins.float] = None) -> builtins.list[tuple[builtins.float, builtins.float]]:
    r"""
    Generate a bouncing-ball curve sampled at regular time intervals.
    
    This function returns a list of ``(height, time)`` pairs describing vertical
    motion under constant gravity. When the ball hits the ground, it bounces back up with a velocity
    scaled by the `elasticity` parameter. Very small rebounds are suppressed so the ball settles to rest.
    
    Parameters:
        height (float):
            Initial height. Must be finite and ``>= 0``.
        velocity (float):
            Initial vertical velocity. Positive values move upward; negative
            values move downward. Must be finite.
        gravity (float, optional):
            Gravitational acceleration (positive). If ``None``, standard Earth
            gravity (9.80665 m/s²) is used.
        elasticity (float, default=1.0):
            Coefficient of restitution in ``[0, 1]``. Controls how much velocity
            is retained after each impact. ``1.0`` is perfectly elastic (no decay) so
            the ball would bounce without losing energy, similar to an LFO, where as
            ``0.0`` removes all energy at the first impact.
        samples_per_second (float, default=100.0):
            Sampling rate in Hz. Must be finite and ``> 0``.
        max_time (float, optional):
            Maximum duration in seconds. Must be finite and ``> 0``. If ``None``,
            a default duration is used.
    
    Returns:
        list[tuple[float, float]]:
            Samples of ``(height, time)``. Heights are guaranteed to be
            non-negative. Times increase according to the sampling rate from ``0`` up to
            ``max_time``.
    
    Raises:
        ValueError:
            If any argument is non-finite, or if any constraint is violated:
    
            - ``height < 0``
            - ``gravity <= 0``
            - ``elasticity`` not between 0 and 1 `
            - ``samples_per_second <= 0``
            - ``max_time <= 0``
    
    Notes:
        The output is computed using a semi-implicit (symplectic) Euler method.
        This produces stable, predictable curves suitable for control and
        modulation.
    
    Examples:
        Basic usage (default gravity, perfectly elastic):
    
        >>> samples = bouncing_ball(height=1.0, velocity=0.0)
    
        A decaying gesture:
    
        >>> samples = bouncing_ball(height=1.0, velocity=0.0, elasticity=0.8, max_time=3.0)
    
        Slower motion under reduced gravity:
    
        >>> samples = bouncing_ball(height=1.0, velocity=0.0, gravity=1.62, max_time=5.0)
    """

def bpm_to_seconds(bpm: builtins.float) -> builtins.float: ...

def create_boids_with_random_positions(flock_size: builtins.int, dimensions: Dimensions) -> builtins.list[Boid]:
    r"""
    Create boids with random positions inside the given dimensions.
    
    This is a convenience function for initializing a flock. Each boid is
    placed uniformly at random within the bounding box defined by
    ``dimensions`` and starts with zero velocity.
    
    Parameters:
        flock_size (int):
            Number of boids to create.
        dimensions (Dimensions):
            World bounds used to generate initial positions.
    
    Returns:
        list[Boid]:
            A list of boids with random in-bounds positions and zero velocity.
    
    Examples:
        >>> dims = Dimensions(-100.0, 100.0, -100.0, 100.0, -100.0, 100.0)
        >>> flock = create_boids_with_random_positions(10, dims)
        >>> len(flock)
        10
    """

def fit(mode: FitMode, min: builtins.float, max: builtins.float, num: builtins.float) -> builtins.float:
    r"""
    Fit a number into the closed interval ``[min, max]`` using the given mode.
    
    If ``num`` is already within ``[min, max]``, it is returned unchanged.
    Otherwise, the chosen ``mode`` determines how values outside the interval are
    mapped back into it.
    
    Args:
        mode (FitMode): The strategy used to map values into the interval.
        min (float): The lower bound of the interval.
        max (float): The upper bound of the interval.
        num (float): The value to fit into the interval.
    
    Returns:
        float: A value within ``[min, max]``.
    
    Raises:
        ValueError: If ``max - min`` is not positive (i.e., ``min >= max``).
        ValueError: If ``min`` or ``max`` are not finite.
    
    Examples:
        Using the interval ``[0, 10]``:
    
        - ``Wrap``: ``fit(Wrap, 0, 10, 12) == 2``; ``fit(Wrap, 0, 10, -4) == 6``
        - ``Reflect``: ``fit(Reflect, 0, 10, 12) == 8``; ``fit(Reflect, 0, 10, -4) == 4``
        - ``Bounce``: ``fit(Bounce, 0, 10, 12) == 8``; ``fit(Bounce, 0, 10, -12) == 2``
        - ``Clamp``: ``fit(Clamp, 0, 10, 12) == 10``; ``fit(Clamp, 0, 10, -4) == 0``
    
    Notes:
        - The interval is treated as *closed*: endpoints are included.
        - Wrap and Reflect mode will revert to Clamp mode when the range between min and
          max is not finite due to an overflow.
        - Bounce mode will revert to Clamp mode when |num| / range is not finite due
          to an overflow.
    """

def fit_list(mode: FitMode, min: builtins.float, max: builtins.float, nums: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]:
    r"""
    Fit a list of numbers into the closed interval ``[min, max]`` using the given mode.
    
    Args:
        mode (FitMode): The strategy used to map values into the interval.
        min (float): The lower bound of the interval.
        max (float): The upper bound of the interval.
        nums (list of float): The values to fit into the interval.
    
    Returns:
        list of float: The fitted values.
    
    Raises:
        ValueError: If ``min`` or ``max`` are not finite.
        ValueError: If ``max - min`` is not positive (i.e., ``min >= max``).
        ValueError: If any of the values in ``nums`` are not finite.
    """

def interval_class(interval: builtins.int) -> builtins.int:
    r"""
    Map a pitch interval (in semitones, any representative mod 12) to interval class 0–6.
    
    ``0`` means unison/octave (interval ≡ 0 mod 12); classes ``1``–``6`` are the usual
    interval classes for distinct pitch classes.
    """

def invert(pc: builtins.int) -> builtins.int:
    r"""
    Invert a pitch class around 0.
    
    This computes the inversion of a pitch class by subtracting it from 12
    and wrapping the result modulo 12.
    
    Args:
        pc (int): The pitch class to invert.
            Must be an integer in the range 0–11.
    
    Returns:
        int: The inverted pitch class, wrapped to the range 0–11.
    
    Raises:
        ValueError: If ``pc`` is not in the range 0–11.
    
    Notes:
        This function uses an i8 under the hood. While it will raise an exception
        if the input is outside the range 0–11, you will get an OverflowError results if
        the input is outside the range of an i8 (i.e. -128 to 127).
    """

def invert_ordered_set(ordered_set: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]:
    r"""
    Invert an ordered pitch-class row around 0.
    
    Each pitch class in the ordered set is inverted by subtracting it from 12
    and wrapping the result modulo 12. The order of the input row is preserved.
    
    Args:
        ordered_set (list[int]): The ordered pitch classes to invert.
            Each pitch class must be in the range 0–11.
    
    Returns:
        list[int]: The inverted ordered set, with each pitch class wrapped to
        the range 0–11.
    
    Raises:
        ValueError: If any pitch class is outside the range 0–11.
    """

def keynum_to_pitch(keynum: builtins.int) -> Pitch:
    r"""
    Build a :class:`Pitch` from a MIDI key number.
    """

def quadratic_bouncing_ball(height: builtins.float, velocity: builtins.float, gravity: typing.Optional[builtins.float] = None, elasticity: builtins.float = 1.0, samples_per_second: builtins.float = 100.0, max_time: typing.Optional[builtins.float] = None) -> builtins.list[tuple[builtins.float, builtins.float]]:
    r"""
    Simulate a bouncing ball and return sampled (height, time) points.
    
    Physics: vertical motion with gravity; at each ground impact the vertical
    velocity is multiplied by ``-elasticity`` (coefficient of restitution).
    
    Args:
        height (float): Initial height in meters (>= 0).
        velocity (float): Initial vertical velocity in m/s (positive = up).
        gravity (float | None): Gravitational acceleration in m/s²; None uses Earth default (9.80665).
        elasticity (float): Coefficient of restitution in [0, 1] (1 = perfectly elastic).
        samples_per_second (float): Sampling rate in Hz (must be > 0).
        max_time (float | None): Simulation end time in seconds; None uses default (10.0).
    
    Returns:
        list[tuple[float, float]]: List of (height, time) tuples at uniform time steps.
    
    Raises:
        ValueError: If height < 0, samples_per_second <= 0, max_time <= 0, or elasticity not in [0, 1].
    """

def quantize(step: builtins.float, value: builtins.float) -> builtins.float:
    r"""
    Quantize a value to the nearest multiple of ``step``.
    
    Returns ``round(value / step) * step`` using IEEE-754 ``f64`` rounding
    (round half away from zero).
    
    Args:
        step (float): The quantization step (grid size). Must be finite and non-zero.
        value (float): The value to quantize.
    
    Returns:
        float: The quantized value.
    
    Raises:
        ValueError: If ``step`` is zero or not finite.
        ValueError: If ``value`` is not finite.
        ValueError: If ``step`` and ``value`` are such that quantization would
            overflow ``f64``.
    
    Notes:
        For IEEE-754 ``f64``, quantization is guaranteed not to overflow when:
    
        .. math::
            |value| \le \min\bigl(\text{f64::MAX} \cdot |step|,\;
                                     \text{f64::MAX} - 0.5\cdot|step|\bigr).
    
    Examples:
        ``quantize(1.0, 2.7) == 3.0``
        ``quantize(1.0, 2.4) == 2.0``
        ``quantize(1.0, 2.5) == 3.0``
        ``quantize(0.5, -1.3) == -1.5``
        ``quantize(0.3, 1.0) == math.isclose(0.9)``
    """

def rhythm_to_seconds(num: builtins.int, den: builtins.int, bpm: builtins.float) -> builtins.float: ...

def satisfy_pc(forte_num: builtins.str, pitch_classes: typing.Sequence[builtins.int]) -> builtins.list[builtins.list[builtins.int]]:
    r"""
    Find pitch-class completions for a Forte set class.
    
    Given a Forte number (e.g. ``"3-11B"``) and a list of distinct pitch classes,
    this function returns all distinct ways to **add** pitch classes so that the
    resulting set has that Forte number (using the same catalog as
    :py:meth:`allegro.pitchclass.PitchClassSet.forte_num`).
    
    The function enumerates all 12 transpositions of the set's Rahn prime form and
    keeps those transpositions that contain the given partial set. For each such
    transposition it returns the sorted list of *missing* pitch classes. Results
    are de-duplicated and returned in lexicographic order.
    
    Args:
        forte_num (str): Forte number label (e.g. ``"3-11B"``).
        pitch_classes (list[int]): Partial pitch-class collection, each 0–11 and unique.
    
    Returns:
        list[list[int]]: Each inner list is a sorted collection of pitch classes
            that can be added so that ``pitch_classes + missing`` has Forte number
            ``forte_num``. Returns an empty list if there are no such completions
            (including when the partial set already realizes the set class).
    
    Raises:
        ValueError: If ``forte_num`` is not found in the Forte catalog.
        ValueError: If any pitch class is outside 0–11 or duplicated.
    """

def transpose(by_semitones: builtins.int, pc: builtins.int) -> builtins.int:
    r"""
    Transpose a pitch class by a given number of semitones.
    
    The pitch class is shifted by the given number of semitones and the
    result is wrapped modulo 12.
    
    Args:
        by_semitones (int): The number of semitones to transpose by.
            Must be in the range -11 to 11.
        pc (int): The pitch class to transpose.
            Must be an integer in the range 0–11.
    
    Returns:
        int: The transposed pitch class, wrapped to the range 0–11.
    
    Raises:
        ValueError: If ``by_semitones`` is outside the range -11 to 11.
        ValueError: If ``pc`` is not in the range 0–11.
    """

def transpose_ordered_set(by_semitones: builtins.int, ordered_set: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]:
    r"""
    Transpose an ordered pitch-class row by a given number of semitones.
    
    Each pitch class in the ordered set is shifted by the given number of
    semitones, preserving the order of the input row. Results are wrapped
    modulo 12.
    
    Args:
        by_semitones (int): The number of semitones to transpose by.
            Must be in the range -11 to 11.
        ordered_set (list[int]): The ordered pitch classes to transpose.
            Each pitch class must be in the range 0–11.
    
    Returns:
        list[int]: The transposed ordered set, with each pitch class wrapped
        to the range 0–11.
    
    Raises:
        ValueError: If ``by_semitones`` is outside the range -11 to 11.
        ValueError: If any pitch class is outside the range 0–11.
    """

def voicings_from_pc_set(pcs: PitchClassSet, octave: builtins.int = 4) -> builtins.list[Voicing]:
    r"""
    Enumerate all voicings of a pitch-class set at a given register.
    
    The first pitch class in ``pcs`` (input order) is placed at ``octave``
    (default 4, e.g. C4 = MIDI 60 when that pitch class is 0). Each permutation
    of the set is realized by walking ascending pitch-class steps along the order.
    """

def voicings_from_pc_set_in_keynum_range(pcs: PitchClassSet, min_keynum: builtins.int, max_keynum: builtins.int) -> builtins.list[Voicing]:
    r"""
    Enumerate voicings whose notes all lie in ``[min_keynum, max_keynum]``.
    
    For each permutation, voices ascend by pitch-class steps along the order, with
    optional octave displacements (+12) between adjacent voices. No anchor register
    is used.
    """

def voicings_from_pc_set_within_span(pcs: PitchClassSet, max_span: builtins.int) -> builtins.list[Voicing]:
    r"""
    Enumerate voicings with span (highest minus lowest note) at most ``max_span``.
    
    Searches MIDI keynums 0–127. Uses the same voice-leading walk as
    ``voicings_from_pc_set_in_keynum_range``, without anchoring.
    """

